version: '2'

services:
  bot:
    image: 'bahertylop/avito-bot:latest'
    build:
      context: bot
    container_name: bot
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${AVITO_BOT_TOKEN}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bot_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bot_db
    ports:
      - "5434:5432"

  frontend:
    image: 'bahertylop/frontend-http-server:latest'
    build:
      context: frontend
    container_name: frontend
    ports:
      - "3000:3000"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: "http frontend:3000"
