version: '2'

services:
  bot:
    image: 'bahertylop/avito-bot:latest'
    build:
      context: bot
    container_name: bot
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${AVITO_BOT_TOKEN}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bot_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=bot_db
    ports:
      - "5434:5432"

  nginx:
    image: 'bahertylop/nginx-frontend:latest'
    build:
      context: ./frontend
    container_name: nginx-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-certs:/etc/nginx/certs # Том для сертификатов
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d bahertylop.ru
    depends_on:
      - nginx

volumes:
  certbot-certs:
#    volumes:
#      - ./ssl:/etc/nginx/ssl
#      - ./frontend/pages:/usr/share/nginx/html