bot:
  token: ${BOT_TOKEN}
  name: car_price_tracking_bot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avito_bot_database
    username: postgres
    password: agroycg592:ggg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081


api:
  url:
    base-url: https://32a1-185-223-93-175.ngrok-free.app
    sign-in: /auth/tg_auth
    refresh: /auth/refresh
    get-profile: /user
    car-positions: /cars
    get-car-brands: /brands
    get-car-models: /models
  constraint:
    min-year-from: 1900
    max-mileage: 5000000
