bot:
  token: ${BOT_TOKEN}
  name: car_price_tracking_bot

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avito_bot_database
    username: postgres
    password: agroycg592:ggg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081


api:
  url:
    sign-in: http://localhost:8080/auth/signin
    refresh: http://localhost:8080/auth/refresh
    get-profile: http://localhost:8080/user
    get-car-positions: http://localhost:8080/cars
    get-brands: http://localhost:8080/brands
    get-models: http://localhost:8080/models
